stages: 
  - build
  - deploy

build_job: 
  stage: build
  image: node:22
  script: 
    - export NVM_DIR="$HOME/.nvm"
    - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' 
    - nvm use 22                                           
    - node -v                                             
    - npm ci
    - npm run build -- --mode production 
  artifacts: 
    paths:
      - dist/
  only:
    - main
  tags:
    - deploy-runner-demo

deploy_job:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - ssh-keyscan ika.mx >> ~/.ssh/known_hosts
    - echo "Conectando a DreamHost..."
    - lftp -d -c "
        open -u $FTP_USER,$FTP_PASSWORD sftp://ika.mx;
        mirror -R --delete --verbose dist /home/ikamx/ika.mx/;
      "
  only:
    - main
  tags:
    - deploy-runner-demo
